import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body id="root">
        <div className="bg-gradient-to-t from-slate-50 via-slate-100 to-slate-200 dark:from-slate-800  dark:to-slate-900 text-black dark:text-white min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
